# This file describes the semantics used for various batch schedulers.

torque:
    exe:        qsub
    resource:   '-l'
    nodes:      '-l nodes={}:ppn={}'
    ppn:        'ppn={}'
    node_type:  '{}'
    account:    '-A'
    depend:     '-W depend={}'
    walltime:   '-l walltime={}'
    delimit:    ':'
    supported_dep: 
        - after
        - afterany
        - afterok
        - afternotok
        - before
        - beforeany
        - beforeok
        - beforenotok

